version: '3'
services:
  mongodb:
    image : mongo
    container_name: mongodb_notes
    hostname: mongodb_notes
    user: 1000:1000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=light
      - MONGO_INITDB_ROOT_PASSWORD=yagami
    volumes:
      - ./data/db/:/data/db/
    ports:
      - 27017:27017
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: memowotoru
    hostname: memowotoru
    user: 1000:1000
    ports:
      - 7331:7331
    volumes:
      - ./src/volume:/usr/src/app/src/volume
    restart: unless-stopped

