version: '3'
services:
  mongodb:
    image : mongo
    container_name: mongodb_notes_patched
    hostname: mongodb_notes_patched
    user: 1000:1000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=light
      - MONGO_INITDB_ROOT_PASSWORD=very_hard_to_guess
    volumes:
      - ./data/db/:/data/db/
    ports:
      - 27018:27017
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: memowotoru_patched
    hostname: memowotoru_patched
    user: 1000:1000
    ports:
      - 7332:7331
    volumes:
      - ./src/volume:/usr/src/app/src/volume
    restart: unless-stopped

